# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - upper_arm_controller

  upper_arm_controller:
    action_ns: follow_joint_trajectory # add
    type: FollowJointTrajectory
    joints:
      - swing_joint
      - boom_joint
      - arm_joint
      - bucket_joint
      - bucket_end_joint