# This config file is used by ros2_control
zx120:
  controller_manager:
    ros__parameters:
      update_rate: 100  # Hz

      upper_arm_controller:
        type: joint_trajectory_controller/JointTrajectoryController


      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

zx120:
  upper_arm_controller:
    ros__parameters:
      joints:
        - swing_joint
        - boom_joint
        - arm_joint
        - bucket_joint
        - bucket_end_joint
      command_interfaces:
        - position
      state_interfaces:
        - position
        # - velocity